apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-gateway-configmap
data:
  resource.fooConfig: |-
    namespace: argo-events
    group: "k8s.io"
    version: "v1"
    kind: "Namespace"
    filter:
      labels:
        name: "hello"
  resource.barConfig: |-
    namespace: argo-events
    group: "argoproj.io"
    version: "v1alpha1"
    kind: "Workflow"
    filter:
      prefix: scripts-bash
      labels:
        workflows.argoproj.io/phase: Failed
