apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: url-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  serviceAccountName: argo-events-sa
  imageVersion: "v0.6"
  repeat: true
  imagePullPolicy: Always
  signals:
    - name: calendar-gateway/calendar.fooConfig
  triggers:
    - name: url-workflow-trigger
      resource:
        namespace: argo-events
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          url:
            path: "https://raw.githubusercontent.com/argoproj/argo/master/examples/hello-world.yaml"
            verifycert: false
